/**
 * Switch Database REST API
 * Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGBody.h
 * 
 * 
 */

#ifndef SWGBody_H_
#define SWGBody_H_

#include <QJsonObject>


#include "SWGList_order.h"
#include "SWGWhereItem.h"
#include <QList>
#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGBody: public SWGObject {
public:
    SWGBody();
    SWGBody(QString* json);
    virtual ~SWGBody();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGBody* fromJson(QString &jsonString);

    QString* getList();
    void setList(QString* list);

    qint32 getCount();
    void setCount(qint32 count);

    qint32 getPage();
    void setPage(qint32 page);

    QString* getWhereType();
    void setWhereType(QString* where_type);

    QList<SWGWhereItem*>* getWhere();
    void setWhere(QList<SWGWhereItem*>* where);

    SWGList_order* getOrder();
    void setOrder(SWGList_order* order);


private:
    QString* list;
    qint32 count;
    qint32 page;
    QString* where_type;
    QList<SWGWhereItem*>* where;
    SWGList_order* order;
};

} /* namespace Swagger */

#endif /* SWGBody_H_ */
