/**
 * Switch Database REST API
 * Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGSetResponse.h
 * 
 * 
 */

#ifndef SWGSetResponse_H_
#define SWGSetResponse_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGSetResponse: public SWGObject {
public:
    SWGSetResponse();
    SWGSetResponse(QString* json);
    virtual ~SWGSetResponse();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGSetResponse* fromJson(QString &jsonString);

    qint64 getResponseTime();
    void setResponseTime(qint64 response_time);

    QString* getResponse();
    void setResponse(QString* response);


private:
    qint64 response_time;
    QString* response;
};

} /* namespace Swagger */

#endif /* SWGSetResponse_H_ */
