/**
 * Switch Database REST API
 * Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SWGWhereItem.h
 * 
 * 
 */

#ifndef SWGWhereItem_H_
#define SWGWhereItem_H_

#include <QJsonObject>


#include <QString>

#include "SWGObject.h"


namespace Swagger {

class SWGWhereItem: public SWGObject {
public:
    SWGWhereItem();
    SWGWhereItem(QString* json);
    virtual ~SWGWhereItem();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGWhereItem* fromJson(QString &jsonString);

    QString* getType();
    void setType(QString* type);

    QString* getColumn();
    void setColumn(QString* column);

    QString* getValue();
    void setValue(QString* value);


private:
    QString* type;
    QString* column;
    QString* value;
};

} /* namespace Swagger */

#endif /* SWGWhereItem_H_ */
